apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "landing-page.fullname" . }}
  labels:
    app: {{ template "landing-page.fullname" . }}
    chart: {{ template "landing-page.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "landing-page.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "landing-page.fullname" . }}
    spec:
      containers:
      - name: landing-page
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MOTD_URL
          value: {{ .Values.motd_url }}
