kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "landing-page.fullname" . }}
  labels:
    app: {{ template "landing-page.fullname" . }}
    chart: {{ template "landing-page.chart" . }}
spec:
  rules:
{{ if .Values.host }}
  - host: {{ .Values.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - backend:
          serviceName: {{ template "landing-page.fullname" . }}
          servicePort: 80
        path: /
