apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ template "alertDatabase.ingesterName" . }}
  labels:
    {{- include "alertDatabase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingester.replicas }}
  selector:
    matchLabels:
      {{- include "alertDatabase.ingesterSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alertDatabase.ingesterSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "alert-database-ingester"
          image: "{{ .Values.ingester.image.repository }}:{{ .Values.ingester.image.tag }}"
          volumeMounts:
            - name: "kafka-client-secret"
              mountPath: "/etc/kafka-client-secret"
              readOnly: True
            - name: "kafka-server-ca-cert"
              mountPath: "/etc/kafka-server-ca-cert"
              readOnly: True
          command:
            - "alertdb-ingester"
            - "--kafka-host={{ .Values.ingester.kafka.cluster }}-kafka-bootstrap:{{ .Values.ingester.kafka.port }}"
            - "--kafka-topic={{ .Values.ingester.kafka.topic }}"
            - "--tls-client-key-location=/etc/kafka-client-secret/user.key"
            - "--tls-client-crt-location=/etc/kafka-client-secret/user.crt"
            - "--tls-server-ca-crt-location=/etc/kafka-server-ca-cert/ca.crt"
            - "--kafka-auth-mechanism=mtls"
            - "--schema-registry-address={{ required "A schema registry URL is required " .Values.ingester.schemaRegistryURL }}"
            - "--gcp-project={{ required "A GCP project is required " .Values.storage.gcp.project }}"
            - "--gcp-bucket-alerts={{ required "A GCP bucket name is required " .Values.storage.gcp.alertBucket }}"
            - "--gcp-bucket-schemas={{ required "A GCP bucket name is required " .Values.storage.gcp.schemaBucket }}"
            {{- if eq .Values.ingester.logLevel "debug" }}
            - "--debug"
            {{- end }}
            {{- if eq .Values.ingester.logLevel "verbose" }}
            - "--verbose"
            {{- end }}

      volumes:
        - name: "kafka-client-secret"
          secret:
            secretName: "{{ .Values.ingester.kafka.user}}"
        - name: "kafka-server-ca-cert"
          secret:
            secretName: "{{ .Values.ingester.kafka.cluster}}-cluster-ca-cert"
      serviceAccountName: "{{ .Values.ingester.serviceAccountName }}"
