apiVersion: v1
name: nublado2
version: 0.0.27
appVersion: 1.0.6
description: Nublado2 JupyterHub installation
home: https://github.com/lsst-sqre/nublado2
maintainers:
  - name: cbanek
sources:
  - https://github.com/lsst-sqre/nublado2
  - https://github.com/lsst-sqre/charts
kubeVersion: '>=1.16.0-0'
