apiVersion: v2
name: alert-stream-broker
version: 1.2.0
description: Kafka broker cluster for distributing alerts
maintainers:
  - name: swnelson
    email: swnelson@uw.edu
appVersion: 1.0.0
type: application
