apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cadc-tap.fullname" . }}-mock-qserv
spec:
  podSelector:
    matchLabels:
      {{- include "cadc-tap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "mock-qserv"
  policyTypes:
    - Ingress
    # Deny all outbound access; MySQL doesn't need to talk to anything.
    - Egress
  ingress:
    # Allow inbound access to mock Qserv from the server.
    - from:
          podSelector:
            matchLabels:
              {{- include "cadc-tap.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "server"
      ports:
        - protocol: "TCP"
          port: 3306
