apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/rewrite-target: "/tap/$1"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://$host/tap/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://$host/api/tap/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.ingress.anonymousAnnotations }}
    {{- toYaml . | indent 4}}
    {{- end }}
  name: {{ template "cadc-tap.fullname" . }}-anonymous
  labels:
    {{- include "cadc-tap.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/api/tap/(availability|capabilities|swagger-ui.*)"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ template "cadc-tap.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
