apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap.fullname" . }}-uws-db
  labels:
    app: {{ template "cadc-tap.fullname" . }}-uws-db
{{ include "cadc-tap.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cadc-tap.fullname" . }}-uws-db
  template:
    metadata:
      labels:
        app: {{ template "cadc-tap.fullname" . }}-uws-db
{{ include "cadc-tap.labels" . | indent 8 }}
    spec:
      containers:
      - name: postgresql
        image: lsstdax/uws-db:{{ .Values.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        resources:
          {{toYaml .Values.aux_resources | nindent 10}}
