apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "semaphore.fullname" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  path: {{ required "vaultSecretsPath must be set" .Values.vaultSecretsPath | quote }}
  type: Opaque
