apiVersion: v1
name: kafka-connect-manager
version: 0.5.1
description: A Helm chart to deploy the kafka connectors used by the EFD
keywords:
  - Kafka, InfluxDB, S3
home: https://kafka-connect-manager.lsst.io/
sources:
  - https://github.com/lsst-sqre/kafka-connect-manager
maintainers:
  - name: afausti
    email: afausti@lsst.org
    url: https://afausti.github.io/
appVersion: 0.8.1
