apiVersion: v1
name: kafka-connect-manager
version: 0.9.5
description: A Helm chart to deploy kafka connectors
keywords:
  - Kafka, InfluxDB, S3, JDBC Sink, MirrorMaker 2
home: https://kafka-connect-manager.lsst.io/
sources:
  - https://github.com/lsst-sqre/kafka-connect-manager
maintainers:
  - name: afausti
    email: afausti@lsst.org
    url: https://afausti.github.io/
appVersion: 0.9.3
