apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-redis
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
spec:
  podSelector:
    # This policy controls inbound and outbound access to the Redis component.
    matchLabels:
      {{- include "gafaelfawr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "redis"
  policyTypes:
    - Ingress
    # Deny all outbound access; Redis doesn't need to talk to anything.
    - Egress
  ingress:
    # Allow inbound access to Redis from all other components.
    - from:
        - podSelector:
            matchLabels:
              {{- include "gafaelfawr.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "frontend"
        - podSelector:
            matchLabels:
              {{- include "gafaelfawr.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "postinstall"
        - podSelector:
            matchLabels:
              {{- include "gafaelfawr.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "tokens"
      ports:
        - protocol: "TCP"
          port: 6379
