{{- if or .Values.serviceAccount.create .Values.cloudsql.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gafaelfawr.serviceAccountName" . }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cloudsql.enabled }}
    iam.gke.io/gcp-service-account: {{ required "cloudsql.serviceAccount must be set to a valid Google service account" .Values.cloudsql.serviceAccount | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
