apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sherlock.serviceAccountName" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "sherlock.serviceAccountName" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "sherlock.serviceAccountName" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "sherlock.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "sherlock.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
