apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "portal.fullname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "0m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "24k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "24k"
    nginx.ingress.kubernetes.io/rewrite-target: "/suit$1$2"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "/suit/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "/portal/app/"
    nginx.ingress.kubernetes.io/proxy-cookie-path: "/suit /portal/app"
    nginx.ingress.kubernetes.io/session-cookie-path: "/portal/app"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Forwarded-Path /firefly;
    {{- if .Values.ingress.gafaelfawrAuthQuery }}
    nginx.ingress.kubernetes.io/auth-method: "GET"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Token"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.ingress.host }}/login"
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.ingress.host }}/auth?{{ .Values.ingress.gafaelfawrAuthQuery }}"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/portal/app(/|$)(.*)"
            pathType: "ImplementationSpecific"
            backend:
              service:
                name: {{ include "portal.fullname" . }}
                port:
                  number: 8080
