apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "portal.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  policyTypes:
    - "Ingress"
  ingress:
    # Allow inbound access from pods (in any namespace) labeled
    # gafaelfawr.lsst.io/ingress: true.
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              gafaelfawr.lsst.io/ingress: "true"
      ports:
        - protocol: "TCP"
          port: 8080
