apiVersion: v1
kind: Service
metadata:
  name: {{ template "nublado.fullname" . }}-js9
  labels:
    name: {{ template "nublado.fullname" . }}-js9
spec:
  type: NodePort
  ports:
  - name: web
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: e
    port: 2718
    targetPort: 2718
    protocol: TCP
  selector:
    name: {{ template "nublado.fullname" . }}-js9
