apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap-postgres.fullname" . }}-uws-db
  labels:
    {{- include "cadc-tap-postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cadc-tap-postgres.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "uws-db"
  template:
    metadata:
      {{- with .Values.uws.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cadc-tap-postgres.labels" . | nindent 8 }}
        app.kubernetes.io/component: "uws-db"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: "postgresql"
          image: "{{ .Values.uws.image.repository }}:{{ .Values.uws.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uws.imagePullPolicy | quote }}
          ports:
            - containerPort: 5432
          {{- with .Values.uws.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "data"
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: "data"
          emptyDir: {}
      {{- with .Values.uws.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uws.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.uws.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
