apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cadc-tap-postgres.fullname" . }}-uws-db
spec:
  podSelector:
    matchLabels:
      {{- include "cadc-tap-postgres.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "uws-db"
  policyTypes:
    - Ingress
    # Deny all outbound access; PostgreSQL doesn't need to talk to anything.
    - Egress
  ingress:
    # Allow inbound access to UWS database from the server.
    - from:
        - podSelector:
            matchLabels:
              {{- include "cadc-tap-postgres.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: "server"
      ports:
        - protocol: "TCP"
          port: 5432
