{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "moneypenny.fullname" . }}
  labels:
    {{- include "moneypenny.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "moneypenny.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow inbound access from pods (in any namespace) labeled
    # gafaelfawr.lsst.io/ingress: true.
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              gafaelfawr.lsst.io/ingress: "true"
      ports:
        - protocol: "TCP"
          port: {{ .Values.service.port }}
{{- end }}
