apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "helpers.fullname" . }}-redis
  name: {{ template "helpers.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "helpers.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "helpers.fullname" . }}-redis
    spec:
      containers:
      - name: redis
        image: redis
        imagePullPolicy: Always
        args:
          - redis-server
          - --appendonly yes
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "1"
        volumeMounts:
          - name: redis-data
            mountPath: "/data"
      volumes:
        - name: redis-data
          {{- if .Values.redis_claim }}
          persistentVolumeClaim:
            claimName: {{ .Values.redis_claim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
