apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vo-cutouts.fullname" . }}-config
  labels:
    {{- include "vo-cutouts.labels" . | nindent 4 }}
data:
  CUTOUT_BUTLER_REPOSITORY: {{ required "config.butlerRepository must be set" .Values.config.butlerRepository | quote }}
  CUTOUT_DATABASE_URL: {{ required "config.databaseUrl must be set" .Values.config.databaseUrl | quote }}
  CUTOUT_SERVICE_ACCOUNT: {{ required "cloudsql.serviceAccount must be set" .Values.cloudsql.serviceAccount | quote }}
  CUTOUT_STORAGE_URL: {{ required "config.gcsBucketUrl must be set" .Values.config.gcsBucketUrl | quote }}
  CUTOUT_TIMEOUT: {{ .Values.config.timeout | quote }}
  CUTOUT_LIFETIME: {{ .Values.config.lifetime | quote }}
  CUTOUT_REDIS_HOST: "{{ template "vo-cutouts.fullname" . }}-redis.{{ .Release.Namespace }}"
  CUTOUT_SYNC_TIMEOUT: {{ .Values.config.syncTimeout | quote }}
  SAFIR_LOG_LEVEL: {{ .Values.config.loglevel | quote }}
