# -- Explicitly sets the name of the deployment and job.
nameOverride: ""

# -- Explicitly sets the full name used for the deployment and job (includes
# the release name).
fullnameOverride: ""

# -- The username of the Kafka user identity used to connect to the broker.
kafkaUserName: alert-stream-simulator

# -- Name of the topic which will hold a static single visit of sample data.
staticTopicName: alerts-static

# -- Name of the topic which will receive the repeated alerts on an interval.
replayTopicName: alerts-simulated

# -- Integer ID to use in the prefix of alert data packets. This should be a
# valid Confluent Schema Registry ID associated with the schema used.
schemaID: 1

# -- Name of a Strimzi Kafka cluster to connect to.
clusterName: alert-broker

# -- Port to connect to on the Strimzi Kafka cluster. It should be an internal
# TLS listener.
clusterPort: 9092

# -- API version of the Strimzi installation's custom resource definitions
strimziAPIVersion: v1beta2

image:
  # -- Source repository for the image which holds the rubin-alert-stream program.
  repository: lsstdm/alert-stream-simulator
  # -- Tag to use for the rubin-alert-stream container.
  tag: v1.0.0
  # -- Pull policy for the Deployment
  imagePullPolicy: IfNotPresent

# -- How often (in seconds) to repeat the sample data into the replay topic.
repeatInterval: 37
