{{- if .Values.ingress.enabled -}}
{{- $fullName := include "datalinker.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "datalinker.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if .Values.ingress.gafaelfawrAuthQuery -}}
    nginx.ingress.kubernetes.io/auth-method: GET
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Token
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.ingress.host }}/login"
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.ingress.host }}/auth?{{ .Values.ingress.gafaelfawrAuthQuery }}"
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host must be set" .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ default "Prefix" .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
