apiVersion: v1
appVersion: "1.1"
description: CADC TAP PostgresSQL service, used for ObsTAP
home: https://github.com/lsst-sqre/tap-postgres
name: cadc-tap-postgres
maintainers:
  - name: cbanek
version: 0.2.0
