apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-request-redirect: $request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Token
    nginx.ingress.kubernetes.io/auth-sign-in: https://{{ .Values.host }}/oauth2/sign_in
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.host }}/auth?capability={{ .Values.user_capability }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = "https://{{ .Values.host }}/oauth2/start?rd=$request_uri";
  name: {{ template "helpers.fullname" . }}-jwt-authorizer-token-ingress
spec:
  rules:
{{ if .Values.host }}
  - host: {{ .Values.host }}
    http:
{{ else }}
  - http:
{{ end }}
      paths:
      - backend:
          serviceName: {{ template "helpers.fullname" . }}-jwt-authorizer
          servicePort: 8080
        path: /auth/token
