apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Forbid everything except GET since this should be a read-only ingress
      # to the schema registry.
      limit_except GET {
        deny all;
      }

spec:
  tls:
  - hosts: [{{ .Values.hostname | quote }}]
    secretName: "{{ .Values.name }}-tls"

  rules:
  - host: {{ .Values.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}
            port:
              # TODO: not configurable in strimzi-registry-operator
              number: {{ .Values.port }}
