# Default values for kafka used in Sasquatch.
cluster:
  # -- Name used for the Kafka cluster, and used by Strimzi for many annotations.
  name: sasquatch

kafka:
  # -- Version of Kafka to deploy.
  version: "3.0.0"
  # -- Number of Kafka broker replicas to run.
  replicas: 3
  storage:
    # -- Size of the backing storage disk for each of the Kafka brokers.
    size: 100Gi
    # -- Name of a StorageClass to use when requesting persistent volumes.
    storageClassName: ""
  # -- Configuration overrides for the Kafka server.
  config:
    # -- Number of minutes for a consumer group's offsets to be retained.
    offsets.retention.minutes: 10080
    # -- Number of days for a topic's data to be retained.
    log.retention.hours: 168
    # -- Maximum retained number of bytes for a topic's data. This is a string
    # -- to avoid YAML type conversion issues for large numbers.
    log.retention.bytes: "644245094400"

zookeeper:
  # -- Number of Zookeeper replicas to run.
  replicas: 3
  storage:
    # -- Size of the backing storage disk for each of the Zookeeper instances.
    size: 100Gi
    # -- Name of a StorageClass to use when requesting persistent volumes.
    storageClassName: ""

connect:
  # -- Number of Kafka Connect replicas to run.
  replicas: 3

# -- A list of usernames for users who should have global admin permissions.
# These users will be created, along with their credentials.
superusers:
  - kafka-admin

