apiVersion: v2
name: redis
version: 1.1.6
description: Simple single-server Redis deployment with configurable storage
sources:
  - https://github.com/lsst-sqre/charts/tree/main/charts/redis
maintainers:
  - name: rra
