apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cadc-tap.fullname" . }}-tap-server
  labels:
    app: {{ template "cadc-tap.fullname" . }}-tap-server
{{ include "cadc-tap.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cadc-tap.fullname" . }}-tap-server
  template:
    metadata:
      labels:
        app: {{ template "cadc-tap.fullname" . }}-tap-server
{{ include "cadc-tap.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "cadc-tap.fullname" . }}-tap-server
        image: lsstdax/lsst-tap-service:{{ .Values.tag }}
        imagePullPolicy: Always
        resources:
          {{toYaml .Values.resources | nindent 10}}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: google-creds
          mountPath: "/etc/creds"
          readOnly: true
        env:
        - name: CATALINA_OPTS
          value: "-Dqservuser.jdbc.username=qsmaster -Dqservuser.jdbc.password= -Dqservuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dqservuser.jdbc.url=jdbc:mysql://{{ .Values.qserv_host }}/ -Dtapuser.jdbc.username=TAP_SCHEMA -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=com.mysql.cj.jdbc.Driver -Dtapuser.jdbc.url=jdbc:mysql://{{ template "cadc-tap.fullname" . }}-tap-schema-db:3306/ -Dca.nrc.cadc.reg.client.RegistryClient.local=true -Duws.jdbc.username=postgres -Duws.jdbc.driverClassName=org.postgresql.Driver -Duws.jdbc.url=jdbc:postgresql://{{ template "cadc-tap.fullname" . }}-uws-db/ -Dca.nrc.cadc.auth.Authenticator=org.opencadc.tap.impl.AuthenticatorImpl -Dgcs_bucket={{ .Values.gcs_bucket }} -Dgcs_bucket_url={{ .Values.gcs_bucket_url }} -Dca.nrc.cadc.util.PropertiesReader.dir=/etc/creds/"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/creds/google_creds.json"
      volumes:
      - name: google-creds
        secret:
          secretName: {{ template "cadc-tap.fullname" . }}-secrets
